### ISSUE TITLE
滑动右边界回弹出现异常

### ISSUE THREAD

**Issue by woaimaomao** [luiing/StretchViewPager#1]
1. 滑动到最后一个page,
2. 继续向左滑动，直到出现decor view.
3. 此时快速去滑动最后一个page
4. viewpager的pager会消失，变成透明背景。

必现，仓库内的demo就可以直接复现。

**Comment by luiing** [comment]
此问题的设备型号是什么，提供个动画发我邮箱luiing@foxmail.com
因为我在360手机，Honor V10没发现此问题

**Comment by woaimaomao** [comment]
经过观察发现，是在滑出rightView的手指释放的时候，待rightView被remove但viewpager的最后一页尚未恢复到边界位置，另一手指立即再次触摸viewpager靠近屏幕左侧区域就会出现。后续提供现象视频。

**Comment by luiing** [comment]
这个问题复现了，你试试fixed分支

**Comment by woaimaomao** [comment]
视频发到邮箱了，fixed分支还是可以复现，我目前的改法是动画结束前，拦掉触摸手势

**Comment by woaimaomao** [comment]
fixed分支没有再复现

**Comment by luiing** [comment]
v0.2.2 had already fixed what cause by anim
